# Generated by Django 4.1.3 on 2022-11-05 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи заявки')),
                ('date_of_target', models.DateField(verbose_name='Заявка на дату')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255, verbose_name='Статус заявки')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=255, verbose_name='Назначение')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=255, verbose_name='Должность')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicStamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp', models.CharField(max_length=255, verbose_name='Марка')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255, verbose_name='Состояние техники')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128, verbose_name='Тип')),
            ],
        ),
        migrations.CreateModel(
            name='Technic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название техники')),
                ('driver', models.ForeignKey(blank=True, default='б/в', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Вадитель')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.technicstatus', verbose_name='Состояние техники')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.technictype', verbose_name='Тип')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.post', verbose_name='Должность')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConstructionSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=512, verbose_name='Адрес')),
                ('foreman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Прораб')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationTechnic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_capacity', models.CharField(blank=True, max_length=128, null=True, verbose_name='Грузоподъемность')),
                ('quantity', models.IntegerField(default=1, verbose_name='Колличество')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.application', verbose_name='Заявка')),
                ('stamp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.technicstamp', verbose_name='Марка')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.technictype', verbose_name='Тип')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=512, verbose_name='Описание')),
                ('quantity', models.CharField(max_length=255, verbose_name='Колличество')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.application', verbose_name='Заявка')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.materialtarget', verbose_name='Назначение')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='constr_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.constructionsite', verbose_name='Объект'),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.applicationstatus', verbose_name='Статус заявки'),
        ),
    ]
