# Generated by Django 4.1.6 on 2023-02-08 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255, verbose_name='Статус заявки')),
            ],
            options={
                'verbose_name': 'Статус заявки',
                'verbose_name_plural': 'Статусы заявок',
            },
        ),
        migrations.CreateModel(
            name='ConstructionSiteStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=256, verbose_name='Статус объекта')),
            ],
            options={
                'verbose_name': 'Статус объекта',
                'verbose_name_plural': 'Статусы объектов',
            },
        ),
        migrations.CreateModel(
            name='DriverTabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Статус водителя')),
                ('date', models.DateField(null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Табель водителя',
                'verbose_name_plural': 'Табеля водителей',
            },
        ),
        migrations.CreateModel(
            name='StaffDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
            },
        ),
        migrations.CreateModel(
            name='StaffForeman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Прораб',
                'verbose_name_plural': 'Прорабы',
            },
        ),
        migrations.CreateModel(
            name='Technic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_information', models.CharField(blank=True, max_length=256, null=True, verbose_name='Идентификационная информация')),
                ('description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Описание')),
                ('attached_driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.staffdriver', verbose_name='Прикрепленный водитель')),
            ],
            options={
                'verbose_name': 'Единица техники',
                'verbose_name_plural': 'Техника',
            },
        ),
        migrations.CreateModel(
            name='TechnicName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название группы техники')),
            ],
            options={
                'verbose_name': 'Название группы техники',
                'verbose_name_plural': 'Название групп техники',
            },
        ),
        migrations.CreateModel(
            name='TechnicStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255, verbose_name='Статус техники')),
            ],
            options={
                'verbose_name': 'Статус техники',
                'verbose_name_plural': 'Статус техники',
            },
        ),
        migrations.CreateModel(
            name='TechnicType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Тип техники')),
                ('short_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Тип техники(коротко)')),
            ],
            options={
                'verbose_name': 'Тип техники',
                'verbose_name_plural': 'Тип техники',
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название переменной')),
                ('value', models.CharField(blank=True, max_length=512, null=True, verbose_name='Значение переменной')),
                ('flag', models.BooleanField(default=False, verbose_name='Флаг переменной')),
                ('description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Переменная',
                'verbose_name_plural': 'Переменные',
            },
        ),
        migrations.CreateModel(
            name='WorkDayTabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Дата')),
                ('status', models.BooleanField(default=True, verbose_name='Рабочий день')),
            ],
            options={
                'verbose_name': 'Рабочий день',
                'verbose_name_plural': 'Рабочие дени',
            },
        ),
        migrations.CreateModel(
            name='TechnicTabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Статус техники')),
                ('date', models.DateField(null=True, verbose_name='Дата')),
                ('technic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.technic', verbose_name='Транспортное средство')),
            ],
            options={
                'verbose_name': 'Табель техники',
                'verbose_name_plural': 'Табеля техники',
            },
        ),
        migrations.CreateModel(
            name='TechnicDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Дата')),
                ('status', models.BooleanField(default=True, verbose_name='Статус техники')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.drivertabel', verbose_name='Водитель техники')),
                ('technic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.technic', verbose_name='Транспортное средство')),
            ],
            options={
                'verbose_name': 'Техника-Водитель',
                'verbose_name_plural': 'Техника-Водители',
            },
        ),
        migrations.AddField(
            model_name='technic',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.technicname', verbose_name='Название техники'),
        ),
        migrations.AddField(
            model_name='technic',
            name='tech_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.technictype', verbose_name='Тип техники'),
        ),
        migrations.CreateModel(
            name='StaffSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сотрудник снабжение',
                'verbose_name_plural': 'Сотрудники снабжение',
            },
        ),
        migrations.CreateModel(
            name='StaffMechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Механик',
                'verbose_name_plural': 'Механики',
            },
        ),
        migrations.CreateModel(
            name='StaffMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('foreman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.staffforeman', verbose_name='Прораб')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
        migrations.CreateModel(
            name='StaffAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Администратор',
                'verbose_name_plural': 'Администраторы',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff', models.CharField(max_length=128, verbose_name='Статус')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.AddField(
            model_name='drivertabel',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.staffdriver', verbose_name='Водитель'),
        ),
        migrations.CreateModel(
            name='ConstructionSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=512, verbose_name='Адрес')),
                ('foreman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.staffforeman', verbose_name='Прораб')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.constructionsitestatus', verbose_name='Статус объекта')),
            ],
            options={
                'verbose_name': 'Строительный объект',
                'verbose_name_plural': 'Строительные объекты',
            },
        ),
        migrations.CreateModel(
            name='ApplicationToday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Дата')),
                ('construction_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.constructionsite', verbose_name='Строительный объект')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.applicationstatus', verbose_name='Статус заявки')),
            ],
            options={
                'verbose_name': 'Заявка на объект',
                'verbose_name_plural': 'Заявки на объект',
            },
        ),
        migrations.CreateModel(
            name='ApplicationTechnic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Описание')),
                ('priority', models.DecimalField(decimal_places=0, default=1, max_digits=3, verbose_name='Приоритет заявки')),
                ('app_for_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.applicationtoday', verbose_name='Заявка на объект')),
                ('technic_driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.technicdriver', verbose_name='Техника-Водитель')),
            ],
            options={
                'verbose_name': 'Заявка на технику',
                'verbose_name_plural': 'Заявки на технику',
            },
        ),
    ]
