# Generated by Django 4.1.6 on 2023-02-12 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technictabel',
            name='technic',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='TechnicTabel',
        ),
    ]
