# Generated by Django 4.1.6 on 2023-02-12 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_remove_technictabel_technic_delete_staff_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TechnicStatus',
        ),
    ]
