# Generated by Django 4.1.4 on 2023-01-01 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_remove_applicationmaterial_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationtechnic',
            name='quantity',
        ),
        migrations.AddField(
            model_name='applicationtechnic',
            name='description',
            field=models.TextField(default=0, max_length=1024, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicationtechnic',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.technic', verbose_name='Техника'),
        ),
    ]
