# Generated by Django 4.1.4 on 2023-01-01 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0004_remove_applicationtechnic_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technic',
            name='driver',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Вадитель'),
        ),
    ]
