# Generated by Django 4.1.6 on 2023-02-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_constructionsite_foreman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionsite',
            name='address',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Адрес'),
        ),
    ]
