# Generated by Django 4.1.5 on 2023-01-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_technic_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtechnic',
            name='vehicle',
            field=models.CharField(default='---', max_length=256, verbose_name='Техника'),
        ),
    ]
