# Generated by Django 4.1.5 on 2023-01-04 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0007_applicationtechnic_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technic',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Вадитель'),
        ),
    ]
