# Generated by Django 4.1.5 on 2023-01-04 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_alter_technic_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technic',
            name='stamp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.technicstamp', verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='technic',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.technictype', verbose_name='Тип'),
        ),
    ]
