# Generated by Django 4.1.5 on 2023-01-07 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_alter_technic_stamp_alter_technic_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.ForeignKey(default='Отсутствует', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='manager.applicationstatus', verbose_name='Статус заявки'),
        ),
    ]
