# Generated by Django 4.1.5 on 2023-01-07 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_alter_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='date_of_create',
        ),
    ]
