# Generated by Django 4.1.5 on 2023-01-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_remove_application_date_of_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionSiteStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=256, verbose_name='Статус объекта')),
            ],
        ),
    ]
