# Generated by Django 4.1.5 on 2023-01-21 14:37

from django.db import migrations, models
import django.db.models.deletion
import manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_constructionsitestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionsite',
            name='status',
            field=models.ForeignKey(default=manager.models.get_def_status_constr_site, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.constructionsitestatus', verbose_name='Статус объекта'),
        ),
    ]
