# Generated by Django 3.2.10 on 2023-01-22 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_constructionsite_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constructionsitestatus',
            options={'verbose_name': 'Статус объекта', 'verbose_name_plural': 'Статусы объектов'},
        ),
    ]
