# Generated by Django 4.1.5 on 2023-01-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_constructionsite_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constructionsitestatus',
            options={'verbose_name': 'Статус объекта', 'verbose_name_plural': 'Статусы объектов'},
        ),
        migrations.AddField(
            model_name='staff',
            name='foreman',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Прораб'),
        ),
    ]
