# Generated by Django 4.1.5 on 2023-01-22 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_alter_constructionsitestatus_options_staff_foreman'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='foreman',
            new_name='id_foreman',
        ),
    ]
