# Generated by Django 4.1.5 on 2023-01-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_rename_foreman_staff_id_foreman'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.BooleanField(default=True, verbose_name='status(T\\F)'),
        ),
    ]
