# Generated by Django 3.2.10 on 2023-01-26 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_alter_constructionsitestatus_options'),
        ('manager', '0019_rename_foreman_staff_id_foreman'),
    ]

    operations = [
    ]
