# Generated by Django 4.1.5 on 2023-01-24 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0019_rename_foreman_staff_id_foreman'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255, verbose_name='Состояние водитель')),
                ('data', models.DateField(null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Состояние водителя',
                'verbose_name_plural': 'Состояние водителей',
            },
        ),
        migrations.CreateModel(
            name='StaffAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Администратор',
                'verbose_name_plural': 'Администраторы',
            },
        ),
        migrations.CreateModel(
            name='StaffDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
            },
        ),
        migrations.CreateModel(
            name='StaffForeman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Прораб',
                'verbose_name_plural': 'Прорабы',
            },
        ),
        migrations.CreateModel(
            name='StaffMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('foreman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.staffforeman', verbose_name='Прораб')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
        migrations.CreateModel(
            name='StaffMechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Механик',
                'verbose_name_plural': 'Механики',
            },
        ),
        migrations.CreateModel(
            name='StaffSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сотрудник снабжение',
                'verbose_name_plural': 'Сотрудники снабжение',
            },
        ),
        migrations.CreateModel(
            name='TechnicDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(null=True, verbose_name='Дата')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.staffdriver', verbose_name='Водитель техники')),
            ],
            options={
                'verbose_name': 'Техника-Водитель',
                'verbose_name_plural': 'Техника-Водители',
            },
        ),
        migrations.CreateModel(
            name='TechnicName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название группы техники')),
            ],
            options={
                'verbose_name': 'Название группы техники',
                'verbose_name_plural': 'Название групп техники',
            },
        ),
        migrations.RemoveField(
            model_name='application',
            name='constr_site',
        ),
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
        migrations.RemoveField(
            model_name='applicationmaterial',
            name='application',
        ),
        migrations.DeleteModel(
            name='MaterialTarget',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='post',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='technic',
            options={'verbose_name': 'Единица техники', 'verbose_name_plural': 'Техника'},
        ),
        migrations.RemoveField(
            model_name='applicationtechnic',
            name='application',
        ),
        migrations.RemoveField(
            model_name='applicationtechnic',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='applicationtechnic',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='technic',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='technic',
            name='load_capacity',
        ),
        migrations.RemoveField(
            model_name='technic',
            name='stamp',
        ),
        migrations.RemoveField(
            model_name='technic',
            name='status',
        ),
        migrations.RemoveField(
            model_name='technic',
            name='type',
        ),
        migrations.AddField(
            model_name='applicationtechnic',
            name='construction_site',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='manager.constructionsite', verbose_name='Строительный объект'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationtechnic',
            name='data',
            field=models.DateField(null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='applicationtechnic',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.applicationstatus', verbose_name='Статус заявки'),
        ),
        migrations.AddField(
            model_name='technic',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='technic',
            name='id_information',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Идентификационная информация'),
        ),
        migrations.AddField(
            model_name='technicstatus',
            name='data',
            field=models.DateField(null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='technicstatus',
            name='technic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='manager.technic', verbose_name='Транспортное средство'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='constructionsite',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.constructionsitestatus', verbose_name='Статус объекта'),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='ApplicationMaterial',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='TechnicStamp',
        ),
        migrations.DeleteModel(
            name='TechnicType',
        ),
        migrations.AddField(
            model_name='technicdriver',
            name='technic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.technic', verbose_name='Название техники'),
        ),
        migrations.AddField(
            model_name='driverstatus',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.staffdriver', verbose_name='Водитель'),
        ),
        migrations.AddField(
            model_name='applicationtechnic',
            name='technic_driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.technicdriver', verbose_name='Техника-Водитель'),
        ),
        migrations.AlterField(
            model_name='constructionsite',
            name='foreman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.staffforeman', verbose_name='Прораб'),
        ),
        migrations.AlterField(
            model_name='technic',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.technicname', verbose_name='Название техники'),
        ),
    ]
