# Generated by Django 3.2.10 on 2023-01-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_merge_20230126_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.BooleanField(default=True, verbose_name='status(T\\F)'),
        ),
    ]
