# Generated by Django 4.1.5 on 2023-01-24 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_driverstatus_staffadmin_staffdriver_staffforeman_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Тип техники')),
                ('short_name', models.CharField(max_length=256, verbose_name='Тип техники(коротко)')),
            ],
            options={
                'verbose_name': 'Тип техники',
                'verbose_name_plural': 'Тип техники',
            },
        ),
        migrations.AddField(
            model_name='technic',
            name='tech_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.technictype', verbose_name='Тип техники'),
        ),
    ]
