# Generated by Django 4.1.5 on 2023-01-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0021_technictype_technic_tech_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technictype',
            name='short_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Тип техники(коротко)'),
        ),
    ]
