# Generated by Django 4.1.5 on 2023-01-24 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0022_alter_technictype_short_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driverstatus',
            options={'verbose_name': 'Статус водителя', 'verbose_name_plural': 'Статус водителей'},
        ),
        migrations.RemoveField(
            model_name='driverstatus',
            name='data',
        ),
        migrations.RemoveField(
            model_name='driverstatus',
            name='driver',
        ),
        migrations.AlterField(
            model_name='driverstatus',
            name='status',
            field=models.CharField(max_length=255, verbose_name='Статус водителя'),
        ),
        migrations.CreateModel(
            name='DriverTabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(null=True, verbose_name='Дата')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.staffdriver', verbose_name='Водитель')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.driverstatus', verbose_name='Состояние водителя')),
            ],
            options={
                'verbose_name': 'Состояние водителя',
                'verbose_name_plural': 'Состояние водителей',
            },
        ),
    ]
