# Generated by Django 4.1.5 on 2023-01-24 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0023_alter_driverstatus_options_remove_driverstatus_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicdriver',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.drivertabel', verbose_name='Водитель техники'),
        ),
        migrations.AlterField(
            model_name='technicdriver',
            name='technic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.technicstatus', verbose_name='Рабочая техника'),
        ),
    ]
