# Generated by Django 4.1.5 on 2023-01-24 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0024_alter_technicdriver_driver_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technicstatus',
            options={'verbose_name': 'Статус техники', 'verbose_name_plural': 'Статус техники'},
        ),
        migrations.RemoveField(
            model_name='technicstatus',
            name='data',
        ),
        migrations.RemoveField(
            model_name='technicstatus',
            name='technic',
        ),
        migrations.AlterField(
            model_name='technicstatus',
            name='status',
            field=models.CharField(max_length=255, verbose_name='Статус техники'),
        ),
        migrations.CreateModel(
            name='TechnicTabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(null=True, verbose_name='Дата')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.technicstatus', verbose_name='Состояние техники')),
                ('technic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.technic', verbose_name='Транспортное средство')),
            ],
            options={
                'verbose_name': 'Состояние техники',
                'verbose_name_plural': 'Состояния техники',
            },
        ),
    ]
