# Generated by Django 4.1.5 on 2023-01-24 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0025_alter_technicstatus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drivertabel',
            options={'verbose_name': 'Табель водителя', 'verbose_name_plural': 'Табеля водителей'},
        ),
        migrations.AlterModelOptions(
            name='technictabel',
            options={'verbose_name': 'Табель техники', 'verbose_name_plural': 'Табеля техники'},
        ),
        migrations.AlterField(
            model_name='technicdriver',
            name='technic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.technictabel', verbose_name='Рабочая техника'),
        ),
    ]
