# Generated by Django 4.1.5 on 2023-01-25 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0026_alter_drivertabel_options_alter_technictabel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationtechnic',
            name='construction_site',
        ),
        migrations.AddField(
            model_name='constructionsite',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.applicationtechnic', verbose_name='Заявки'),
        ),
    ]
