# Generated by Django 4.1.5 on 2023-01-25 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0027_remove_applicationtechnic_construction_site_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructionsite',
            name='application',
        ),
        migrations.AddField(
            model_name='applicationtechnic',
            name='construction_site',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='manager.constructionsite', verbose_name='Строительный объект'),
            preserve_default=False,
        ),
    ]
