# Generated by Django 4.1.5 on 2023-01-25 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0028_remove_constructionsite_application_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationtechnic',
            name='construction_site',
        ),
        migrations.RemoveField(
            model_name='applicationtechnic',
            name='data',
        ),
        migrations.RemoveField(
            model_name='applicationtechnic',
            name='status',
        ),
        migrations.CreateModel(
            name='ApplicationToday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(null=True, verbose_name='Дата')),
                ('construction_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.constructionsite', verbose_name='Строительный объект')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.applicationstatus', verbose_name='Статус заявки')),
            ],
            options={
                'verbose_name': 'Заявка на объект',
                'verbose_name_plural': 'Заявки на объект',
            },
        ),
    ]
