# Generated by Django 4.1.5 on 2023-01-25 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0029_remove_applicationtechnic_construction_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtoday',
            name='app_technic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.applicationtechnic', verbose_name='Заявка на технику'),
        ),
    ]
