# Generated by Django 4.1.5 on 2023-01-25 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0030_applicationtoday_app_technic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationtoday',
            name='app_technic',
        ),
        migrations.AddField(
            model_name='applicationtechnic',
            name='app_for_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.applicationtoday', verbose_name='Заявка на объект'),
        ),
    ]
