# Generated by Django 4.1.5 on 2023-01-25 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0033_alter_staff_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtoday',
            name='construction_site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manager.constructionsite', verbose_name='Строительный объект'),
        ),
    ]
