# Generated by Django 4.1.5 on 2023-01-28 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0034_alter_applicationtoday_construction_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtoday',
            name='list_of_applications',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Список заявок'),
        ),
        migrations.AlterField(
            model_name='applicationtoday',
            name='construction_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.constructionsite', verbose_name='Строительный объект'),
        ),
    ]
