# Generated by Django 4.1.5 on 2023-01-28 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0035_applicationtoday_list_of_applications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationtoday',
            name='list_of_applications',
        ),
        migrations.AlterField(
            model_name='applicationtechnic',
            name='app_for_day',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='manager.applicationtoday', verbose_name='Заявка на объект'),
            preserve_default=False,
        ),
    ]
