# Generated by Django 4.1.5 on 2023-01-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0036_remove_applicationtoday_list_of_applications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtechnic',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Описание'),
        ),
    ]
