# Generated by Django 4.1.5 on 2023-01-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0037_alter_applicationtechnic_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivertabel',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус водителя'),
        ),
        migrations.DeleteModel(
            name='DriverStatus',
        ),
    ]
