# Generated by Django 4.1.5 on 2023-01-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0038_alter_drivertabel_status_delete_driverstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDayTabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(null=True, verbose_name='Дата')),
                ('status', models.BooleanField(default=True, verbose_name='Рабочий день')),
            ],
            options={
                'verbose_name': 'Рабочий день',
                'verbose_name_plural': 'Рабочие дени',
            },
        ),
    ]
