# Generated by Django 4.1.5 on 2023-01-28 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0039_workdaytabel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workdaytabel',
            old_name='data',
            new_name='date',
        ),
    ]
