# Generated by Django 4.1.5 on 2023-01-28 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0040_rename_data_workdaytabel_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationtoday',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='drivertabel',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='technicdriver',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='technictabel',
            old_name='data',
            new_name='date',
        ),
    ]
