# Generated by Django 4.1.5 on 2023-01-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0041_rename_data_applicationtoday_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technictabel',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус техники'),
        ),
    ]
