# Generated by Django 4.1.5 on 2023-01-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0042_alter_technictabel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtechnic',
            name='priority',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=3, verbose_name='Приоритет заявки'),
        ),
    ]
