# Generated by Django 4.1.5 on 2023-02-01 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0043_applicationtechnic_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicdriver',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус водителя'),
        ),
        migrations.AlterField(
            model_name='technicdriver',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.staffdriver', verbose_name='Водитель техники'),
        ),
    ]
