# Generated by Django 4.1.5 on 2023-02-01 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0044_technicdriver_status_alter_technicdriver_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicdriver',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.staffdriver', verbose_name='Водитель техники'),
        ),
    ]
