# Generated by Django 4.1.5 on 2023-02-01 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0045_alter_technicdriver_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicdriver',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.drivertabel', verbose_name='Водитель техники'),
        ),
        migrations.AlterField(
            model_name='technicdriver',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус техники'),
        ),
        migrations.AlterField(
            model_name='technicdriver',
            name='technic',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='manager.technic', verbose_name='Транспортное средство'),
            preserve_default=False,
        ),
    ]
