# Generated by Django 3.2.10 on 2023-02-03 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_staff_status'),
        ('manager', '0021_staff_status'),
        ('manager', '0046_alter_technicdriver_driver_and_more'),
    ]

    operations = [
    ]
