# Generated by Django 3.2.10 on 2023-02-03 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0047_merge_20230203_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='status',
        ),
        migrations.AddField(
            model_name='technic',
            name='attached_driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.staffdriver', verbose_name='Прикрепленный водитель'),
        ),
    ]
