# Generated by Django 4.1.6 on 2023-02-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0048_auto_20230203_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название переменной')),
                ('value', models.CharField(blank=True, max_length=512, null=True, verbose_name='Значение переменной')),
                ('flag', models.BooleanField(default=False, verbose_name='Флаг переменной')),
            ],
            options={
                'verbose_name': 'Переменная',
                'verbose_name_plural': 'Переменные',
            },
        ),
    ]
