# Generated by Django 4.1.6 on 2023-02-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0049_variable'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Описание'),
        ),
    ]
